services:
  maxtg_bot1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: maxtg_bot1
    env_file:
      - .env.bot1
    environment:
      BOT_NAME: maxtg_bot1
    restart: unless-stopped

  maxtg_bot2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: maxtg_bot2
    env_file:
      - .env.bot2
    environment:
      BOT_NAME: maxtg_bot2
    restart: unless-stopped

  maxtg_bot3:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: maxtg_bot3
    env_file:
      - .env.bot3
    environment:
      BOT_NAME: maxtg_bot3
    restart: unless-stopped

  maxtg_bot_6e_parents:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: maxtg_bot_6e_parents
    env_file:
      - .env.bot_6e_parents
    environment:
      BOT_NAME: maxtg_bot_6e_parents
    restart: unless-stopped
